Repository axibase/charts-language-service, pull requests merged in 2019-08, with the labels that each got.

#5 Generate types dynamically
  .gitignore
  types/checkPriority.d.ts
  types/completionProvider.d.ts
  types/config.d.ts
  types/configTree/configTree.d.ts
  types/configTree/configTreeValidator.d.ts
  types/configTree/section.d.ts
  types/constants.d.ts
  types/defaultSetting.d.ts
  types/field.d.ts
  types/formatter.d.ts
  types/hoverProvider.d.ts
  types/index.d.ts
  types/keywordHandler.d.ts
  types/languageService.d.ts
  types/messageUtil.d.ts
  types/possibleValue.d.ts
  types/regExpressions.d.ts
  types/relatedSettingsRules/index.d.ts
  types/relatedSettingsRules/presenceValidation/noUselessSettings/forSeries.d.ts
  types/relatedSettingsRules/presenceValidation/noUselessSettings/forWidget.d.ts
  types/relatedSettingsRules/presenceValidation/noUselessSettings/index.d.ts
  types/relatedSettingsRules/presenceValidation/noUselessSettings/simultaneousTimeSettings.d.ts
  types/relatedSettingsRules/presenceValidation/requiredSettings.d.ts
  types/relatedSettingsRules/utils/condition.d.ts
  types/relatedSettingsRules/utils/interfaces.d.ts
  types/relatedSettingsRules/valueValidation/colorsThresholds.d.ts
  types/relatedSettingsRules/valueValidation/forecastAutoCountAndEigentripleLimit.d.ts
  types/relatedSettingsRules/valueValidation/forecastEndTime.d.ts
  types/relatedSettingsRules/valueValidation/forecastStartTime.d.ts
  types/relatedSettingsRules/valueValidation/startEndTime.d.ts
  types/resourcesProviderBase.d.ts
  types/script.d.ts
  types/sectionStack.d.ts
  types/setting.d.ts
  types/textRange.d.ts
  types/time/index.d.ts
  types/time/timeParseError.d.ts
  types/time/timeParser.d.ts
  types/time/utils.d.ts
  types/util.d.ts
  types/validator.d.ts
Labels: done

#3 Evaluate settings
  src/defaultSetting.ts
  src/relatedSettingsRules/index.ts
  src/relatedSettingsRules/presenceValidation/requiredSettings.ts
  src/relatedSettingsRules/valueValidation/forecastSsaGroupAutoUnion.ts
  src/relatedSettingsRules/valueValidation/forecastSsaGroupManualGroups.ts
  src/resources/descriptions.md
  src/resources/dictionary.json
  src/resources/dictionary.schema.json
  src/setting.ts
  src/test/required.test.ts
  src/test/type.test.ts
  src/validator.ts
Labels: done, enhancement

#9 Evaluate-expression can be multiline
  src/resources/dictionary.json
  src/test/repetition.test.ts
Labels: done

#6 Add travis config
  .travis.yml
Labels: done

#11 Force upper case for date template string
  src/time/timeParser.ts
Labels: done

#13 Added "collapsible" and "summary-text"
  src/constants.ts
  src/relatedSettingsRules/presenceValidation/requiredSettings.ts
  src/resources/descriptions.md
  src/resources/dictionary.json
Labels: done

#14 Support for evaluate-expression blocks
  src/completionProvider.ts
  src/configTree/configTree.ts
  src/configTree/section.ts
  src/formatter.ts
  src/relatedSettingsRules/index.ts
  src/relatedSettingsRules/presenceValidation/metricsAndEvaluateExpr.ts
  src/relatedSettingsRules/presenceValidation/noUselessSettings/index.ts
  src/relatedSettingsRules/presenceValidation/noUselessSettings/simultaneousTimeSettings.ts
  src/relatedSettingsRules/presenceValidation/requiredSettings.ts
  src/relatedSettingsRules/utils/interfaces.ts
  src/relatedSettingsRules/valueValidation/colorsThresholds.ts
  src/relatedSettingsRules/valueValidation/forecastAutoCountAndEigentripleLimit.ts
  src/relatedSettingsRules/valueValidation/forecastEndTime.ts
  src/relatedSettingsRules/valueValidation/forecastSsaGroupAutoUnion.ts
  src/relatedSettingsRules/valueValidation/forecastSsaGroupManualGroups.ts
  src/relatedSettingsRules/valueValidation/forecastStartTime.ts
  src/relatedSettingsRules/valueValidation/startEndTime.ts
  src/resources/descriptions.md
  src/resources/snippets/snippets.json
  src/test/completionProvider.test.ts
  src/test/indents.test.ts
  src/test/required.test.ts
  src/textRange.ts
  src/validator.ts
Labels: done

#17 Check blocks for nesting
  src/config.ts
  src/keywordHandler.ts
  src/regExpressions.ts
  src/test/expr.test.ts
  src/test/script.test.ts
  src/test/sql.test.ts
  src/validator.ts
Labels: done

#18 Allow `source = message-stat`
  src/resources/dictionary.json
  src/test/type.test.ts
Labels: done

#19 CSV variable is undefined
  src/regExpressions.ts
  src/test/undefinedVar.test.ts
  src/validator.ts
Labels: done

#12 Formatter refactoring
  src/formatter.ts
  src/jsFormatter.ts
  src/languageService.ts
  src/nestedCodeFormatter.ts
  src/test/completionProvider.test.ts
  src/test/expr.test.ts
  src/test/formatBlankLines.test.ts
  src/test/hover.test.ts
  src/test/indents.test.ts
  src/test/scriptFormatting.test.ts
  src/test/sql.test.ts
  src/test/test.ts
Labels: done, enhancement

#22 Update dictionary settings
  src/resources/dictionary.json
Labels: done

#21 Preserve comments
  src/formatter.ts
  src/jsFormatter.ts
  src/test/scriptFormatting.test.ts
Labels: bug, done

#26 Preserve blank line after tags
  src/formatter.ts
  src/test/indents.test.ts
Labels: bug

#30 Allow 'path' at [widget] level
  src/resources/dictionary.json
Labels: done

#28 Handle [column] settings
  src/formatter.ts
  src/regExpressions.ts
  src/test/columnSections.test.ts
  src/validator.ts
Labels: done

#27 Invalid JavaScript formatting
  src/jsFormatter.ts
  src/test/scriptFormatting.test.ts
Labels: done

#35 Duplicate columns are allowed
  src/resources/dictionary.json
  src/test/columnSections.test.ts
Labels: done

#34 Fix: [column] interpreted as [tags]
  src/test/columnSections.test.ts
  src/validator.ts
Labels: bug, done

#38 Replace links
  src/test/freemarker.test.ts
  src/validator.ts
Labels: done
