Repository axibase/charts-language-service, pull requests merged in 2019-09, with the labels that each got.

#32 Comments indents
  src/formatter.ts
  src/nestedCodeFormatter.ts
  src/regExpressions.ts
  src/test/columnSections.test.ts
  src/test/comentsFormating.test.ts
Labels: done, enhancement

#42 Fix '=' sign indents
  src/formatter.ts
  src/test/indents.test.ts
Labels: done

#43 Change column section logic
  src/formatter.ts
  src/regExpressions.ts
  src/sectionStack.ts
  src/test/columnSections.test.ts
  src/test/indents.test.ts
  src/test/test.ts
  src/validator.ts
Labels: done

#54 Fix if condition
  src/keywordHandler.ts
  src/regExpressions.ts
  src/test/ifCondition.test.ts
Labels: bug, done

#56 auto-scale excludes max/min-range-force
  src/resources/dictionary.json
Labels: done

#67 Improve comments formatting
  src/formatter.ts
  src/regExpressions.ts
  src/test/comentsFormating.test.ts
Labels: bug, done

#46 Improve sections formatting inside keywords
  src/constants.ts
  src/formatter.ts
  src/regExpressions.ts
  src/test/expr.test.ts
  src/test/indents.test.ts
  src/test/scriptFormatting.test.ts
  src/test/sql.test.ts
  src/test/type.test.ts
Labels: done, enhancement

#68 Improve dealiases handling
  src/test/alias.test.ts
  src/validator.ts
Labels: bug, done

#62 Validate each item of `multiple` setting list
  src/setting.ts
  src/test/type.test.ts
  src/validator.ts
Labels: done, enhancement

#69 Calendar validation rules
  src/regExpressions.ts
  src/relatedSettingsRules/index.ts
  src/relatedSettingsRules/valueValidation/calendarPaletteTicks.ts
  src/relatedSettingsRules/valueValidation/calendarTimespan.ts
  src/relatedSettingsRules/valueValidation/summarizePeriodTimespan.ts
  src/test/calendarValidationRules.test.ts
  src/time/index.ts
  src/time/intervalParser.ts
  src/time/timeParseError.ts
  src/time/timeParser.ts
Labels: done

#73 Snippets formatting improvements
  src/resources/snippets/snippets.json
Labels: done

#74 No aliases check for non-script settings
  src/test/alias.test.ts
  src/validator.ts
Labels: bug, done

#70 Inline script formatting
  src/formatter.ts
  src/jsFormatter.ts
  src/nestedCodeFormatter.ts
  src/regExpressions.ts
  src/test/comentsFormating.test.ts
  src/test/expr.test.ts
  src/test/formatBlankLines.test.ts
  src/test/indents.test.ts
  src/test/scriptFormatting.test.ts
  src/test/sql.test.ts
  src/test/var.test.ts
Labels: done, enhancement

#71 Treemap validation enhancements
  src/relatedSettingsRules/index.ts
  src/relatedSettingsRules/presenceValidation/noUselessSettings/forWidget.ts
  src/relatedSettingsRules/presenceValidation/requiredSettings.ts
  src/relatedSettingsRules/valueValidation/paletteTicks.ts
  src/resources/dictionary.json
  src/setting.ts
  src/test/calendarValidationRules.test.ts
  src/test/findUseless.test.ts
  src/test/paletteTicks.test.ts
  src/test/required.test.ts
  src/test/size.test.ts
Labels: done, enhancement

#80 Fix indent increment in multiline comments
  src/regExpressions.ts
  src/test/comentsFormating.test.ts
Labels: bug, done

#77 Forecast baseline settings validation
  src/relatedSettingsRules/presenceValidation/requiredSettings.ts
  src/resources/descriptions.md
  src/resources/dictionary.json
Labels: documentation

#79 Allow multiple `rule`
  src/resources/dictionary.json
Labels: done

#76 Make [tag] to [tags] warning specific
  src/messageUtil.ts
Labels: done, enhancement

#81 Add `on-title-click` setting
  src/resources/descriptions.md
  src/resources/dictionary.json
Labels: done

#84 Fix 'size' set as 'alias' false error
  src/setting.ts
  src/test/size.test.ts
Labels: done
